### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: Node (086_upsample) has input size 1 not in range [min=2, max=2].

### ISSUE THREAD

**Issue by zcunyi** [Cw-zero/TensorRT_yolo3_module#2]
onnx.onnx_cpp2py_export.checker.ValidationError: Node (086_upsample) has input size 1 not in range [min=2, max=2].

**Comment by JWSunny** [comment]
@zcunyi  hello, when use the yolov3-416.weights convert to onnx, i meet the same error; do you solve it now?

**Comment by JWSunny** [comment]
Excuse me,  i have solved it.

**Comment by luthfianto** [comment]
@JWSunny how did you solve it?
